# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "elasticsearch" do |elasticsearch|
    elasticsearch.vm.box = "bento/centos-6.7"
    elasticsearch.vm.network :private_network, ip: "172.17.1.101"
    elasticsearch.vm.hostname = "elasticsearch.local"
    elasticsearch.vm.provision :shell, :path => "provision/elasticsearch.sh"
  end

  config.vm.define "fluentd" do |fluentd|
    fluentd.vm.box = "bento/centos-6.7"
    fluentd.vm.network :private_network, ip: "172.17.1.102"
    fluentd.vm.hostname = "fluentd.local"
    fluentd.vm.provision :shell, :path => "provision/fluentd.sh"
  end

  # synced_folder
  config.vm.synced_folder "./", "/vagrant", disabled: true
  config.vm.synced_folder "../playbook/", "/playbook", :mount_options => ["dmode=775", "fmode=664"]

  # customize
  # config.vm.provider "virtualbox" do |vb|
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
end
